In [1]:
import numpy as np

In [2]:
a=np.array([[1,2,3,9,5,6,7],[6,54,4,3,4,3,4]])
print(a.size)
print(a.dtype)
print(a)
print(a.itemsize)
print(a.shape)
#print(a.reshape(7,2))
np.zeros(2)
np.ones(2)
np.empty(2)

14
int32
[[ 1  2  3  9  5  6  7]
 [ 6 54  4  3  4  3  4]]
4
(2, 7)


array([1., 1.])

In [3]:
a

array([[ 1,  2,  3,  9,  5,  6,  7],
       [ 6, 54,  4,  3,  4,  3,  4]])

In [4]:
a*a

array([[   1,    4,    9,   81,   25,   36,   49],
       [  36, 2916,   16,    9,   16,    9,   16]])

In [5]:
a**a

array([[        1,         4,        27, 387420489,      3125,     46656,
           823543],
       [    46656,         0,       256,        27,       256,        27,
              256]])

In [6]:
1/a

array([[1.        , 0.5       , 0.33333333, 0.11111111, 0.2       ,
        0.16666667, 0.14285714],
       [0.16666667, 0.01851852, 0.25      , 0.33333333, 0.25      ,
        0.33333333, 0.25      ]])

In [7]:
a+a

array([[  2,   4,   6,  18,  10,  12,  14],
       [ 12, 108,   8,   6,   8,   6,   8]])

In [8]:
a*2

array([[  2,   4,   6,  18,  10,  12,  14],
       [ 12, 108,   8,   6,   8,   6,   8]])

## slicing

In [9]:
arr=np.array([1,2,3,4,5,6,7])


In [10]:
arr1=arr[2:5]
arr1

array([3, 4, 5])

In [11]:
arr1[2]=100
arr


array([  1,   2,   3,   4, 100,   6,   7])

In [12]:
a

array([[ 1,  2,  3,  9,  5,  6,  7],
       [ 6, 54,  4,  3,  4,  3,  4]])

In [13]:
a[0]
a[0,3]=10000

In [14]:
a

array([[    1,     2,     3, 10000,     5,     6,     7],
       [    6,    54,     4,     3,     4,     3,     4]])

In [15]:
a1 = np.array([[1,2],[3,4],[5,6]])  
print(a1[0,1])  
print(a1[1,0])  
print(a1[2,1])  

2
3
6


In [16]:
arr

array([  1,   2,   3,   4, 100,   6,   7])

In [17]:
arr.max()

100

In [18]:
arr.min()

1

In [19]:
arr.sum()

123

In [20]:
a

array([[    1,     2,     3, 10000,     5,     6,     7],
       [    6,    54,     4,     3,     4,     3,     4]])

In [21]:
a.max(axis=0)

array([    6,    54,     4, 10000,     5,     6,     7])

In [22]:
a.min(axis=1)

array([1, 3])

In [23]:
a.sum(axis=0)

array([    7,    56,     7, 10003,     9,     9,    11])

In [24]:
a.sum(axis=1)

array([10024,    78])

In [25]:
a.sqrt()

AttributeError: 'numpy.ndarray' object has no attribute 'sqrt'

In [ ]:
np.sqrt(a)

In [ ]:
np.std(a)

In [ ]:
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[1,2,3],[4,5,6]])
print(c+d)
print(c-d)
print(c*d)
print(c/d)


In [ ]:
c1=np.array([[1,2,3],[4,5,6]])
d1=np.array([[100,200,300],[4000,5000,6000]])
print(np.vstack((c1,d1)))
print(np.hstack((c1,d1)))

## arithmetic


In [27]:
import numpy as np
arr9=np.empty((3,2),dtype="int32")

In [28]:
arr9

array([[-217452416,        521],
       [         0,          0],
       [    131074, 1701667186]])

In [31]:
np.zeros((3,2),dtype="float64")

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [32]:
np.ones((2,2),dtype="bool_")

array([[ True,  True],
       [ True,  True]])

## ASARRAY

In [ ]:
l=[1,2,3,4,5,6,7]  
print(type(l))
a = np.asarray(l);  
print(type(a))  
print(a) 

In [34]:
l1=[[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]]  
print(type(l1))
a = np.asarray(l1);  
print(type(a))  
print(a) 

<class 'list'>
<class 'numpy.ndarray'>
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


## FROMBUFFER

In [37]:
import numpy as np  
l3 = b'hello world'  
print(type(l3))  
a = np.frombuffer(l3, dtype = "S1")  
print(a)  
print(type(a))  

<class 'bytes'>
[b'h' b'e' b'l' b'l' b'o' b' ' b'w' b'o' b'r' b'l' b'd']
<class 'numpy.ndarray'>


## ARRANAGE

In [43]:
num=np.arange(0,100,10,int)

In [44]:
print(num)

[ 0 10 20 30 40 50 60 70 80 90]


## LINSPACE


In [59]:
lin1 = np.linspace(10, 20,1,endpoint=True,dtype="int")  
print("The array over the given range is ",lin1)  

The array over the given range is  [10]


In [46]:
lin1 = np.linspace(10, 20, 10)  
print("The array over the given range is ",lin1) 

The array over the given range is  [10.         11.11111111 12.22222222 13.33333333 14.44444444 15.55555556
 16.66666667 17.77777778 18.88888889 20.        ]


In [47]:
lin1 = np.linspace(10, 20, 3)  
print("The array over the given range is ",lin1) 

The array over the given range is  [10. 15. 20.]


In [62]:
lin1 = np.linspace(10,7,endpoint=False)  
print("The array over the given range is ",lin1) 

The array over the given range is  [10.    9.94  9.88  9.82  9.76  9.7   9.64  9.58  9.52  9.46  9.4   9.34
  9.28  9.22  9.16  9.1   9.04  8.98  8.92  8.86  8.8   8.74  8.68  8.62
  8.56  8.5   8.44  8.38  8.32  8.26  8.2   8.14  8.08  8.02  7.96  7.9
  7.84  7.78  7.72  7.66  7.6   7.54  7.48  7.42  7.36  7.3   7.24  7.18
  7.12  7.06]


## longspace


In [64]:
arr = np.logspace(10, 20, num = 5, endpoint = True,base=2,dtype="int")  
print("The array over the given range is ",arr) 

The array over the given range is  [   1024    5792   32768  185363 1048576]


## brodcasting

In [69]:
a = np.array([1,2,3,4,5,6,7]) 
print(a.itemsize())
b = np.array([2,4,6,8,10,12,14,19])  
c = a*b;  
print(c)  

TypeError: 'int' object is not callable

In [72]:
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])  
b = np.array([2,4,6,8])  
print("\nprinting array a..")  
print(a)  
print("\nprinting array b..")  
print(b)  
print("\nAdding arrays a and b ..")  
c = a + b;  
print(c)  


printing array a..
[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]

printing array b..
[2 4 6 8]

Adding arrays a and b ..
[[ 3  6  9 12]
 [ 4  8 11 14]
 [12 24 45 11]]


## array iteration

In [4]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("original array",a)
at=a.T
print("tranpose",at)
for x in np.nditer(a):
    print(x,end=" ")

original array [[1 2 3]
 [4 5 6]
 [7 8 9]]
tranpose [[1 4 7]
 [2 5 8]
 [3 6 9]]
1 2 3 4 5 6 7 8 9 

In [8]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("original array",a)
at=a.T
print("tranpose",at)
c=at.copy(order="C")
d=at.copy(order="F")
print("copy==",c)
for x in np.nditer(a):
    print(x,end=" ")
for x in np.nditer(c):
    print("copy c==",c,end=" ")
for x in np.nditer(d):
    print("copy d==",d,end=" ")

original array [[1 2 3]
 [4 5 6]
 [7 8 9]]
tranpose [[1 4 7]
 [2 5 8]
 [3 6 9]]
copy== [[1 4 7]
 [2 5 8]
 [3 6 9]]
1 2 3 4 5 6 7 8 9 copy c== [[1 4 7]
 [2 5 8]
 [3 6 9]] copy c== [[1 4 7]
 [2 5 8]
 [3 6 9]] copy c== [[1 4 7]
 [2 5 8]
 [3 6 9]] copy c== [[1 4 7]
 [2 5 8]
 [3 6 9]] copy c== [[1 4 7]
 [2 5 8]
 [3 6 9]] copy c== [[1 4 7]
 [2 5 8]
 [3 6 9]] copy c== [[1 4 7]
 [2 5 8]
 [3 6 9]] copy c== [[1 4 7]
 [2 5 8]
 [3 6 9]] copy c== [[1 4 7]
 [2 5 8]
 [3 6 9]] copy d== [[1 4 7]
 [2 5 8]
 [3 6 9]] copy d== [[1 4 7]
 [2 5 8]
 [3 6 9]] copy d== [[1 4 7]
 [2 5 8]
 [3 6 9]] copy d== [[1 4 7]
 [2 5 8]
 [3 6 9]] copy d== [[1 4 7]
 [2 5 8]
 [3 6 9]] copy d== [[1 4 7]
 [2 5 8]
 [3 6 9]] copy d== [[1 4 7]
 [2 5 8]
 [3 6 9]] copy d== [[1 4 7]
 [2 5 8]
 [3 6 9]] copy d== [[1 4 7]
 [2 5 8]
 [3 6 9]] 

In [9]:
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])  
  
print("\nPrinting the array:\n")  
  
print(a)  
  
print("\nPrinting the transpose of the array:\n")  
at = a.T  
  
print(at)  
  
print("\nIterating over the transposed array\n")  
  
for x in np.nditer(at):  
    print(x, end= ' ')  
  
print("\nSorting the transposed array in C-style:\n")  
  
print("\nIterating over the C-style array:\n")  
for x in np.nditer(at, order = 'C'):  
    print(x,end=' ')  


Printing the array:

[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]

Printing the transpose of the array:

[[ 1  2 10]
 [ 2  4 20]
 [ 3  5 39]
 [ 4  6  3]]

Iterating over the transposed array

1 2 3 4 2 4 5 6 10 20 39 3 
Sorting the transposed array in C-style:


Iterating over the C-style array:

1 2 10 2 4 20 3 5 39 4 6 3 

## BITWISE OPERATOR

In [17]:
a=10;
b=12;
print("binary representation of a",bin(a))
print("binary representation of a",bin(b))
print(" and=",np.bitwise_and(a,b))
print("or=",np.bitwise_or(a,b))
print("binar representation and=",bin(np.bitwise_and(a,b)))
print("binary reoresentation or=",bin(np.bitwise_or(a,b)))


binary representation of a 0b1010
binary representation of a 0b1100
 and= 8
or= 14
binar representation and= 0b1000
binary reoresentation or= 0b1110


In [19]:
arr = np.array([20],dtype = np.uint8)  
print("Binary representation:",np.binary_repr(20,8))  

  
print(np.invert(arr))  
  
print("Binary representation: ", np.binary_repr(235,8))  

Binary representation: 00010100
[235]
Binary representation:  11101011


## string method

## 1--->>>> add

In [1]:
import numpy as np   
print("Concatenating two string arrays:")  
print(np.char.add(['welcome','Hi'], [' to Javatpoint', ' read python'] ))  

Concatenating two string arrays:
['welcome to Javatpoint' 'Hi read python']


In [3]:
print(np.char.multiply("hello ",3)) 

hello hello hello 


In [4]:
print(np.char.center("Javatpoint", 20, '*'))  

*****Javatpoint*****


In [5]:
print(np.char.split("Welcome To Javatpoint"),sep = " ")  

['Welcome', 'To', 'Javatpoint']


## mathemetic function

In [8]:
arr=np.array([[1,2,3],[4,5,6]])
arr.sum(axis=1)

array([ 6, 15])

In [12]:
b=np.array([[1,2,3],[4,5,6]])
np.dot(arr,b.T)

array([[14, 32],
       [32, 77]])

In [11]:
np.cross(arr,b)

array([[0, 0, 0],
       [0, 0, 0]])

## sorting

In [15]:
arr=np.array([[10,12,13,100,1,100],[10,12,9,89,77,43]])
np.sort(arr,axis=1)

array([[  1,  10,  12,  13, 100, 100],
       [  9,  10,  12,  43,  77,  89]])

In [16]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [30]:
b=np.array([1,90,12,35,76,12,32,43,4,0,45,1000,65,98,98,65])
c=np.sort(b)
np.shape(b)
c.reshape(4,4)
b.reshape(8,2)
np.argsort(c)
print(np.argmin(b))
print(np.argmin(c))
print(np.argmax(b))
print(np.argmax(c))

9
0
11
15


## copies and view


In [39]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,19,10,11]])
print(a)
print(id(a))
b=a
print(b)
print(id(b))
b.shape=4,3
print(b)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 19 10 11]]
1901982934736
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 19 10 11]]
1901982934736
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [19 10 11]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [19 10 11]]


1901985738320
